 version: "3.9" 
 
 services: 
   database: 
    image: postgres:latest 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: spamoverflow 
    volumes: 
      - ./data/db:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrator -d spamoverflow"]
      interval: 10s
      timeout: 5s
      retries: 5
   app: 
    build:
      context: .
      dockerfile: Dockerfile.dev 
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/spamoverflow 
    ports: 
      - "6400:6400" 
    depends_on: 
      - database