 version: "3.9" 
 
 services: 
   database: 
    image: postgres:latest 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: todo 
    volumes: 
      - ./data/db:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrator -d todo"]
      interval: 10s
      timeout: 5s
      retries: 5
   app: 
    build: . 
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/todo 
    ports: 
      - "8080:8080" 
    depends_on: 
      - database